### ISSUE TITLE
Giving up 6.0.0

### ISSUE THREAD

**Issue by celiovasconcelos** [pushlink/pushlink-phonegap#16]
@luisvsilva @rscarvalho 

Hello @rscarvalho 

Now I see. We MUST release a version without braking changes because of the nature of our project.
This is not a kind of library that the user can get troubles in their tests. When the user notice that there was a API change... is too late. The device will be in the "road" and pushlink will not be able to send updates anymore.

So I decided to unpublish the `6.0.0`. Agreed?

**Comment by celiovasconcelos** [comment]
Unpublished! 

It stayed available for `2h`. 😞 

Rodolfo suggested method overloading :

Change `PushLink.start(package, apiKey, callbacks)` to `PushLink.start({package: 'x.y.z', apiKey: 'xxx', callback: function() {} });` checking if the first argument is an object.

**Comment by celiovasconcelos** [comment]
Also, I just asked to npm support to erase the unpublished versions so that we can `reuse` those versions.

'5.5.1': '2017-07-13T12:41:19.429Z'
'5.5.0-1': '2017-07-13T14:48:18.018Z'
'5.5.0-2': '2017-07-13T17:15:39.401Z'
'6.0.0': '2017-07-17T11:03:50.773Z'

Sorry @luisvsilva for stucking you...

**Comment by luisvsilva** [comment]
I will work on the method overloading approach and submit a push request soon.

Fully agree with the decision.

**Comment by celiovasconcelos** [comment]
`6.0.1` released

**Comment by luisvsilva** [comment]
Thanks for this guys!!!

Regards

Luis
