### ISSUE TITLE
Update build dependencies

### ISSUE THREAD

**Issue by celiovasconcelos** [pushlink/pushlink-phonegap#25]
[Cordova paramedic](https://github.com/apache/cordova-paramedic) seems to be outdated.

- It has old and [dangerous dependencies](https://github.com/pushlink/pushlink-cordova-plugin/network/dependencies)
- It has build problems related to Android SDK folders. (I'm not sure if this is a paramedic or cordova problem)
```
Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
Looked here: /Users/celiovasconcelos/Library/Android/sdk/tools/templates/gradle/wrapper
```
Some [workarounds...](https://stackoverflow.com/questions/42613882/error-could-not-find-gradle-wrapper-within-android-sdk-might-need-to-update-yo).

**Comment by rscarvalho** [comment]
Cordova-paramedic still is the de-facto way to test cordova plugins unfortunately, so I'm closing this.
