### ISSUE TITLE
update to pushlink 5.5

### ISSUE THREAD

**Issue by lunow** [pushlink/pushlink-phonegap#6]
When would be the plugin updated to current pushlink version? Looking especially on ninja update strategy.

**Comment by celiovasconcelos** [comment]
Hi @lunow,
We are going to release it ASAP. We are holding a little to investigate an issue reported (by support email) by other user.

**Comment by lunow** [comment]
Thanks for the response. Looking forward to it.

**Comment by celiovasconcelos** [comment]
@lunow It's done!
